name: broken_ci
on:
  - push
jobs:
  example:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install gometalinter
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        go get -u github.com/alecthomas/gometalinter
        gometalinter --install
