name: try docker action
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: print secrets
      run: |
          echo $Secret1 >> src/.env
          cat src/.env 
      shell: bash
      env:
        Secret1: ${{secrets.SECRET1}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
       name: secret 
       # A file, directory or wildcard pattern that describes what to upload
       path: src/.env   
