name: try docker action
on:
  check_suite:
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: print secrets
      run: |
          echo $DEV_ENV_FILE  >> src/.env
          cat src/.env 
      shell: bash
      env:
        DEV_ENV_FILE : ${{secrets.SECRET1}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       name: DEV_ENV_FILE  
       path: src/.env   
