name: try docker action
on:
  push:
jobs:
  example:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v2.2.0
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        include-packages: "Synapse 40.1"
