name: try docker action
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - name: print secrets
      run: |
          echo $Secret1 >> src/.env
          cat src/.env 
      shell: bash
      env:
        Secret1: ${{secrets.SECRET1}}
