name: try docker action
on:
  release:
    types:
    - published
jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [identity, db, api, ui]
    steps:
    
    - name: test dockercontainer_action
      run: echo hello
