name: mysql
on: 
  push: 

jobs:
  release:
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: laravel_tags
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - run: |
          echo -e "[mysqld]\nsecure-file-priv=''" | sudo tee -a /etc/mysql/my.cnf
          cat /etc/mysql/my.cnf
          sudo service mysql restart
      - run: |
          mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -uroot  -e "SELECT @@global.secure_file_priv"
   # - name: Dump GitHub context
   #   env:
   #     GITHUB_CONTEXT: ${{ toJson(github) }}
   #   run: echo "$GITHUB_CONTEXT" 
 
