name: mysql
on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    services: 
      psql:
        image: "postgres"
        volumes:
         - ./seed.sql:/docker-entrypoint-initdb.d/init.sql
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Create test database
      run: |
        sudo systemctl start mysql
        mysql -uroot -proot < databases/tracker/create_databases.sql
