name: mysql
on: push

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v1
    - run: |
         cd /var/run
         ls
    - name: Create test database
      run: |
        sudo systemctl start mysql
        mysql -uroot -proot < databases/tracker/create_databases.sql
