name: push to bitbucket
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: 'master'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
         
    - run: | 
        git remote rename origin upstream 
        git remote add origin git@bitbucket.org:jingzhuyan/test2.git 
        git config --global user.email "yanjingzhu123@outlook.com"
        git config --global user.name "yanjingzhu"
        git push origin master
        
