name: Test
on: 
  pull_request:
    types: [labeled]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2
      if: contains( github.event.pull_request.labels.*.name, "needs-attention" )
