name: Test
on: push
jobs:
  job1:
    if: github.ref == 'ref/heads/master'
    runs-on: ubuntu-latest
    steps: 
    - run: echo hello
  job2:
    runs-on: ubuntu-latest
    steps: 
    - run: echo hello
    
