name: Test

on: 
  issues:

jobs:

  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2-beta
      with:
        fetch-depth: 0
    - uses: actions/first-interaction@v1
 	    with: 
 	      repo-token: ${{ secrets.GITHUB_TOKEN }}
 	      issue-message: '${{ github.actor }} just so you are aware we have a dedicated Working Group for the network.'
 	      pr-message: '${{ github.actor }} just so you are aware we have a dedicated Working Group for the network.'
   # - run: echo $SECRET1 &  az webapp config appsettings set --settings WEBSITE_NODE_DEFAULT_VERSION=$SECRET1 
    #  env: 
     #   SECRET1: ${{secrets.SECRET1}}
      
         
     
