
name: Test
on: 
  push:
    branches: 
      - master
  pull_request_review:
    types: [submitted, edited, dismissed]


jobs:

  job2:
    runs-on: ubuntu-latest

    steps: 
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
