name: Test
on: pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  
    - name: automerge
      uses: "pascalgn/automerge-action@ccae530ae13b6af67a7a2009c266fe925844e658"
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    
