name: Test
on: 
  pull_request:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.labels) }}
      run: |
         echo "$GITHUB_CONTEXT"
         echo "contains status: needs-attention ${{ contains(github.event.pull_request.labels.*.name, 'status: needs-attention') }}"
         echo ${github.event.pull_request.labels.*.name.length}}

    - uses: actions/checkout@v2
      if:  contains(github.event.pull_request.labels.*.name, 'status needs-attention' )
