name: Test
on: pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
  
    - name: Automatically Merge PR
      uses: plm9606/automerge_actions@1.0.0
      with:
        # The PR label name you want to use when merge PR automatically.
        # GitHub WebHook Secret Token
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
