name: Test
on: 
  pull_request:
    types: [labeled, edited]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
    
    - name: get label length
      id: getlength
      env:
          labels: ${{ toJson(github.event.pull_request.labels) }}
      run: |
         echo "$labels"
         echo $labels | jq '. | length'
         LL=" $labels | jq '. | length' "
         echo "::set-output name=Label_length::$LL"

    - name: Dump output message
      if : steps.getlength.outputs.Label_length >= 1
      run: echo $COMMIT_MS
      env:
        COMMIT_MS: ${{ steps.getlength.outputs.Label_length }}

    - uses: actions/checkout@v2
      if: |
        contains(github.event.pull_request.labels.*.name, 'status: needs-attention')
