name: add comment
filter:
  true: [ master, develop, testing ]
  false: [ '**', '!**-wip' ]
on: 
  issues:
    types: [opened]
  push:
    branches: ${{ filter.${{ github.repository_owner == 'my-main' || github.repository_owner == 'maintainer-id' }} }}
    paths:
      - '.github/workflows/TestPR.yml'
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: fail when reopen
      if: github.event.action == 'opened'
      run: jjjjj
    - run:  echo $github_context
      env: 
        github_context: ${{ tojson(github) }}
    - name: Create comment for issue
      if: github.event_name == 'issues'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            @${{ github.actor }} just so you are aware we have a dedicated Working Group for the network.
    - name: Create comment for PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.number)}}
        body: |
            @${{ github.actor }} just so you are aware we have a dedicated Working Group for the network.
   # - run: echo $SECRET1 &  az webapp config appsettings set --settings WEBSITE_NODE_DEFAULT_VERSION=$SECRET1 
   #   env: 
   #     SECRET1: ${{secrets.SECRET1}}
      
         
     
