name: update status

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ouzi-dev/commit-status-updater@v1.0.4
      with:
        status: "${{ job.status }}"
        description: "hello linter"
