name: update status

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - run: |
        ssh-keygen -f id_rsa -t rsa -N ''
        ls ~/.ssh
        cat /home/runner/.ssh/id_rsa.pub >> /home/runner/.ssh/authorized_keys
        chmod 640 /home/runner/.ssh/authorized_keys
        sudo service ssh reload
        echo "================================================="
        ssh localhost -p 22
 #>> /root/.ssh/authorized_keys 
  #ssh -o StrictHostKeyChecking=no root@localhost
   # - run: |
    #    ssh runner@localhost -p 22 -t
  
