name: update status

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - run: |
        mkdir  ~/.ssh 
        cd .ssh
        ssh-keygen
        cat id_rsa.pub >> authorized_keys
        chmod 640 authorized_keys
        sudo service ssh reload
        ssh localhost -p 22
 #>> /root/.ssh/authorized_keys 
  #ssh -o StrictHostKeyChecking=no root@localhost
   # - run: |
    #    ssh runner@localhost -p 22 -t
  
