name: update status

on: check_suite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 127.0.0.1
        username: 'runner'
        password: ''
        port: '22'
        script: ssh runner@localhost -p 22 -t
   # - run: |
    #    ssh runner@localhost -p 22 -t
  
