name: update status

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - run: |
        cat /home/runner/.ssh/id_rsa.pub 
        ssh root@localhost  -p 22
 #>> /root/.ssh/authorized_keys 
  #ssh -o StrictHostKeyChecking=no root@localhost
   # - run: |
    #    ssh runner@localhost -p 22 -t
  
