name: update status

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up ssh-agent
      uses: yakuhzi/action-ssh-agent@v1
      with:
        public: ${{ secrets.SSH_PUBLIC_KEY }}
        private: ${{ secrets.SSH_PRIVATE_KEY }}
    - run: |
        cat /home/runner/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
        ssh root@localhost  -p 22
        
  #ssh -o StrictHostKeyChecking=no root@localhost
   # - run: |
    #    ssh runner@localhost -p 22 -t
  
