name: update status

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |

        sudo apt-get install ssh
        cat /etc/ssh/sshd_config
        ssh -o StrictHostKeyChecking=no root@localhost
  
  #ssh -o StrictHostKeyChecking=no root@localhost
   # - run: |
    #    ssh runner@localhost -p 22 -t
  
